codecov:
  branch: master       # the branch to show by default, inherited from your git repository settings
  strict_yaml_branch: master
coverage:
  precision: 2
  round: down
  range: "70...90"
  status:
    project:
      default:
        target: 70
        if_no_uploads: error
        set_pending: yes
        if_no_uploads: error
    patch: off

comment:
  layout: "header, diff, changes, suggestions, sunburst"
  behavior: default
